# Generated by Django 3.0.8 on 2020-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
